name: Test

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "setup variables"
        run: echo -e "\n//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN\n$AUTH_TOKEN" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      - run: npm i
      - run: npm t
